PlaceFinder\Bundle\DomainBundle\Entity\PlaceUpdateProposal:
    properties:
        id:
            type: integer
            groups: [default]
        place:
            exlude: true
            groups: [default]
