PlaceFinder\Bundle\DomainBundle\Entity\UpdateProposal:
    properties:
        createDt:
            type: DateTime<"Y-m-d H:i:s">
#            groups: [newsletter, newsletter-detailed]
        operation:
            type: string
#            groups: [newsletter, newsletter-detailed]
        field:
            type: string
#            groups: [newsletter, newsletter-detailed]
        value:
            type: string
#            groups: [newsletter, newsletter-detailed]
