PlaceFinder\DomainBundle\Entity\PlaceCategory:
    properties:
        id:
            type: integer
            groups: [default]
        name:
            type: string
            groups: [default]
