PlaceFinder\DomainBundle\Entity\Place:
    properties:
        id:
            type: integer
            groups: [default]
        createDt:
            type: DateTime<"Y-m-d H:i:s">
            groups: [default]
        updateDt:
            type: DateTime<"Y-m-d H:i:s">
            groups: [default]
        name:
            type: string
            groups: [default]
        latitude:
            type: double
            groups: [default]
        longitude:
            type: double
            groups: [default]
        deletedAt:
            type: DateTime<"Y-m-d H:i:s">
            groups: [default]
        isOnline:
            type: boolean
            groups: [default]
        placeCategories:
            type: ArrayCollection<PlaceFinder\DomainBundle\Entity\PlaceCategory>
            groups: [default]
