place_finder_api:
    resource: PlaceFinder\Bundle\APIBundle\Controller\PlaceController
    prefix:   /api
    type:     rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
