place_finder_admin:
    resource: PlaceFinder\AdminBundle\Controller\AdminController
    prefix:   /admin
    type:     annotation

place_finder_api:
    resource: PlaceFinder\APIBundle\Controller\PlaceController
    prefix:   /api
#    type:     rest
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
