# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    # JMS Doctrine
#    jms_serializer.object_constructor:
#        alias: "jms_serializer.doctrine_object_constructor"
#        public: "false"
