<?php

namespace PlaceFinder\DomainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceCategoryRepository extends EntityRepository
{
}
