<?php

namespace PlaceFinder\DomainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PlaceFinder\APIBundle\Filter\PlacesFilter;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    /**
     * Finds entities by a set of criteria.
     *
     * @param PlacesFilter $placesFilter
     * @param array|null   $orderBy
     * @param int|null     $limit
     * @param int|null     $offset
     *
     * @return array
     */
    public function getAllFiltered(PlacesFilter $placesFilter, array $orderBy = null, $limit = null, $offset = null)
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder('p')
            ->select('p')
            ->from($this->getClassName(), 'p')
            ->innerJoin('p.placeCategories', 'pc');

        // Online
        if (null !== $placesFilter->getIsOnline()) {
            $qb->andWhere('p.isOnline = :isOnline')
                ->setParameter('isOnline', (boolean) $placesFilter->getIsOnline());
        } else {
            $qb->andWhere('p.isOnline = :isOnline')
                ->setParameter('isOnline', true);
        }


        $qb->setFirstResult($offset);
        $qb->setMaxResults($limit);

        return $qb;
    }
}
