<?php

namespace PlaceFinder\Bundle\DomainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OpeningTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningTimeRepository extends EntityRepository
{
}
